# Generated by Django 5.1.4 on 2024-12-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ultraAdmin', 'Ultra Admin'), ('superAdmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('distributer', 'Distributer'), ('retailer', 'Retailer')], default='superAdmin', max_length=20),
        ),
    ]
