# Generated by Django 5.1.4 on 2024-12-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/store_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/product_images/'),
        ),
    ]
