# Generated by Django 5.1.4 on 2024-12-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_store_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
