# Generated by Django 5.1.4 on 2025-01-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_issued',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
